development:
  adapter: mysql2
  encoding: utf8
  database: kiwitime_development
  pool: 5
  username: root
  password:
  host: localhost

pre:
  adapter: mysql2
  encoding: utf8
  database: kiwitime_pre
  pool: 5
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: kiwitime_test
  pool: 5
  username: root
  password:
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: kiwitime_production
  pool: 5
  username: root
  password:
  host: localhost